name: pos_fe
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.4+1

environment:
  sdk: ">=3.1.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  sqflite: ^2.3.0
  go_router: ^13.1.0
  dio: ^5.4.0
  equatable: ^2.0.5
  path: ^1.8.3
  cron: ^0.6.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.2
  sqflite_common_ffi: ^2.3.2+1
  sqlite3_flutter_libs: ^0.5.20
  image: ^4.1.3
  crypto: ^3.0.3
  # esc_pos_utils: ^1.1.0
  # flutter_esc_pos_utils: ^1.0.0
  thermal_printer: ^1.0.5
  animations: ^2.0.11
  webview_flutter: ^4.7.0
  scrollable_positioned_list: ^0.3.8
  path_provider: ^2.1.3
  sentry_flutter: ^8.3.0
  encrypt: ^5.0.1
  hotkey_manager: ^0.2.3
  permission_handler: ^11.3.1
  archive: ^3.6.1
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  synchronized: ^3.1.0+1
  device_info_plus: ^10.1.2
  autoscale_tabbarview: ^1.0.2
  package_info_plus: ^8.0.2
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    - assets/logo/maroon.svg
    - assets/logo/white.svg
    - assets/logo/maroon_only_pos.svg
    - assets/logo/white_only_pos.svg
    - assets/logo/ruby_pos.png
    - assets/logo/ruby_pos_icon.png
    - assets/images/empty-item.svg
    - assets/images/empty-search.svg
    - assets/images/barcode-scanner.svg
    - assets/images/barcode.svg
    - assets/images/inventory.svg
    - assets/images/icon-success.svg
    - assets/images/supermarket-illustration.png
    - assets/images/caution.png
    - assets/images/3d-success.png
    - assets/images/3d-fail.png
    - assets/ic_launcher.png
    - assets/images/logo-topgolf.png
    - assets/images/logo-topgolf.jpg
    - assets/images/found.png
    - assets/icon/ruby_pos_icon.png
    - assets/icon/ruby_pos_logo.png
    - assets/images/ruby_pos.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# msix_config:
#   display_name: Test POS
#   publisher_display_name: Company Name
#   identity_name: company.suite.flutterapp
#   msix_version: 1.0.0.0
#   # logo_path: C:\Users\Beone\Documents\devRaymond\pos_fe\assets\logo\maroon.svg
#   capabilities: internetClient, location, microphone, webcam

msix_config:
  display_name: Test POS
  app_installer: #<-- app installer configuration
    publish_folder_path: C:\Users\Beone
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
  msix_version: 1.0.3.0

# Splash Screen
flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/ruby_pos_icon.png
  android_12:
    image: assets/icon/ruby_pos_icon.png
  android: true
  ios: true

  # Launcher Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ruby_pos_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/ruby_pos_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/ruby_pos_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/ruby_pos_icon.png"
