const receiptcontents = [
  {
    "row": 0,
    "content": "logo",
    "fontsize": 2,
    "isbold": 1,
    "alignment": 1,
  },
  {
    "row": 1,
    "content": "storeName",
    "fontsize": 2,
    "isbold": 1,
    "alignment": 1,
  },
  {
    "row": 2,
    "content": "emptyLine",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 3,
    "content": "draftWatermarkTop",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 4,
    "content": "docNumAndDatetime",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  // {
  //   "row": 4,
  //   "content": "datetime",
  //   "fontsize": 1,
  //   "isbold": 0,
  //   "alignment": 2,
  // },
  {
    "row": 5,
    "content": "cashRegister",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 6,
    "content": "employeeCodeAndName",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 7,
    "content": "horizontalLine",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  // {
  //   "row": 6,
  //   "content": "emptyLine",
  //   "fontsize": 1,
  //   "isbold": 0,
  //   "alignment": 0,
  // },
  {
    "row": 8,
    "content": "items",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 9,
    "content": "emptyLine",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 10,
    "content": "totalPrice",
    "fontsize": 2,
    "isbold": 1,
    "alignment": 0,
  },
  {
    "row": 11,
    "content": "taxDetails",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 12,
    "content": "horizontalLine",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  // {
  //   "row": 11,
  //   "content": "totalQty",
  //   "fontsize": 2,
  //   "isbold": 1,
  //   "alignment": 0,
  // },
  // {
  //   "row": 12,
  //   "content": "emptyLine",
  //   "fontsize": 1,
  //   "isbold": 0,
  //   "alignment": 0,
  // },
  {
    "row": 13,
    "content": "mopAlias",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 14,
    "content": "horizontalLine",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 15,
    "content": "customer",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 1,
  },
  {
    "row": 16,
    "content": "horizontalLine",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 17,
    "content": "draftWatermarkBottom",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },

  {
    "row": 18,
    "content": "footer01",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 1,
  },
  {
    "row": 19,
    "content": "emptyLine",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  // {
  //   "row": 13,
  //   "content": "customRow1",
  //   "fontsize": 1,
  //   "isbold": 0,
  //   "alignment": 1,
  //   "customvalue":
  //       "Belanja dari Rumah via\nwaonline.testmart.co.id\nUntuk informasi dan saran, hubungi\nIG @testmart.id - WA 0810 0000 0000\nPT TESTMART JAYA\nNPWP: 13.000.000.8-888.888"
  // },
  {
    "row": 20,
    "content": "address1",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 1,
  },
  {
    "row": 21,
    "content": "address2",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 1,
  },
  {
    "row": 22,
    "content": "city",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 1,
  },
  {
    "row": 23,
    "content": "emptyLine",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 0,
  },
  {
    "row": 24,
    "content": "receiptBarcode",
    "fontsize": 1,
    "isbold": 0,
    "alignment": 1,
  },
];
